name: ${project.name}
main: net.azisaba.psgui.PlayerSettingsGUI
version: ${project.version}
authors: ["siloneco", "YukiLeafX"]
description: ${project.description}
website: ${project.url}
softdepend: ["PlayerSettings"]
api-version: 1.16
commands:
  settings:
    permission: playersettingsgui.command.settings
    aliases: ["setting", "playersetting", "playersettings"]
permissions:
  playersettingsgui.command.settings:
    default: true